# Training PPO tiny tackers
### Run on Google Colab for superior training efficiency and download model to models folder in Tiny-Tackers directory

- - - - - - - - - - - - - - - - - - - -
## Training a PPO Base Model on Gabo-Tor Environment
- Windward Buoy (only has to reach it)
- - - - - - - - - - - - - - - - - - - -

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Set directory to tiny_tackers
%cd "/content/drive/My Drive/tiny_tackers"

/content/drive/My Drive/tiny_tackers

In [ ]:
# Install and import dependencies
!pip install stable-baselines3 gymnasium pygame

import os
import sys
import time
import pandas as pd
import gymnasium as gym

from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy

from gymnasium.wrappers import RecordVideo

Requirement already satisfied: stable-baselines3 in /usr/local/lib/python3.12/dist-packages (2.8.0)
Requirement already satisfied: gymnasium in /usr/local/lib/python3.12/dist-packages (1.2.3)
Requirement already satisfied: pygame in /usr/local/lib/python3.12/dist-packages (2.6.1)
Requirement already satisfied: numpy<3.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.0.2)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.10.0+cu128)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (3.1.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (3.10.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (0.0.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3.0,>=2.3->stable-baselines3) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3.0,>=2.3->stable-baselines3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3.0,>=2.3->stable-baselines3) (3.0.3)

In [ ]:
# Set path to retrieving the base environment
BASE_ENV_PATH = "/content/drive/My Drive/tiny_tackers/gym_sailing_environments/gym_sailing_gabo-tor"
sys.path.append(BASE_ENV_PATH)

In [ ]:
# Import environment and ensure it's comming from the correct path. Ending in tiny_tackers/gym_sailing_environments/gym_sailing_gabo-tor/gym_sailing/__init__.py
import gym_sailing
print(gym_sailing.__file__)

/content/drive/My Drive/tiny_tackers/gym_sailing_environments/gym_sailing_gabo-tor/gym_sailing/__init__.py

/usr/local/lib/python3.12/dist-packages/gymnasium/envs/registration.py:636: UserWarning: WARN: Overriding environment SailboatDiscrete-v0 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")
/usr/local/lib/python3.12/dist-packages/gymnasium/envs/registration.py:636: UserWarning: WARN: Overriding environment Motorboat-v0 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")

In [ ]:
# Specifify that the environment is going to be one where continuous actions are possible not discrete
ENV_ID = "Sailboat-v0"

In [ ]:
# Create directory for storing the base model, videos, and metrics
models_dir = "models/ppo/base"
videos_dir = "videos/ppo/base"
metrics_dir = "metrics"

os.makedirs(models_dir, exist_ok=True)
os.makedirs(videos_dir, exist_ok=True)
os.makedirs(metrics_dir, exist_ok=True)

In [ ]:
# Make and define training and evaluation environments (render mode is none because vizualizing significantly slows down training and evaluation)
def make_env(render_mode=None):
    env = gym.make(ENV_ID, render_mode=render_mode)
    env = Monitor(env)
    return env

train_env = make_env()
eval_env = make_env()

In [ ]:
# Improve efficiency with parallel environments
from stable_baselines3.common.env_util import make_vec_env
train_env = make_vec_env(lambda: make_env(), n_envs=4)

In [ ]:
# Train PPO for 1_000_000 timesteps and save the training time in seconds
model = PPO(
    policy="MlpPolicy",
    env=train_env,
    learning_rate=3e-4,
    n_steps=1024,
    batch_size=64,
    gamma=0.99,
    verbose=1,
)

start = time.time()
model.learn(
    total_timesteps=1_000_000,
    progress_bar=True,
)

training_time_seconds = time.time() - start

Using cuda device

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Output()

/usr/local/lib/python3.12/dist-packages/ipywidgets/widgets/widget_output.py:111: DeprecationWarning:
Kernel._parent_header is deprecated in ipykernel 6. Use .get_parent()
  if ip and hasattr(ip, 'kernel') and hasattr(ip.kernel, '_parent_header'):

/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(

Streaming output truncated to the last 5000 lines.
|    loss                 | 3.81        |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.000745   |
|    std                  | 1.01        |
|    value_loss           | 15.1        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 728          |
|    ep_rew_mean          | -236         |
| time/                   |              |
|    fps                  | 853          |
|    iterations           | 19           |
|    time_elapsed         | 91           |
|    total_timesteps      | 77824        |
| train/                  |              |
|    approx_kl            | 0.0018041099 |
|    clip_fraction        | 0.00632      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.916        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.66         |
|    n_updates            | 180          |
|    policy_gradient_loss | -0.00028     |
|    std                  | 1            |
|    value_loss           | 25.3         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 775          |
|    ep_rew_mean          | -239         |
| time/                   |              |
|    fps                  | 849          |
|    iterations           | 20           |
|    time_elapsed         | 96           |
|    total_timesteps      | 81920        |
| train/                  |              |
|    approx_kl            | 0.0016831451 |
|    clip_fraction        | 0.0166       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.881        |
|    learning_rate        | 0.0003       |
|    loss                 | 17.9         |
|    n_updates            | 190          |
|    policy_gradient_loss | -0.00166     |
|    std                  | 1.01         |
|    value_loss           | 40.7         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 808          |
|    ep_rew_mean          | -241         |
| time/                   |              |
|    fps                  | 845          |
|    iterations           | 21           |
|    time_elapsed         | 101          |
|    total_timesteps      | 86016        |
| train/                  |              |
|    approx_kl            | 0.0015784267 |
|    clip_fraction        | 0.0104       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.43        |
|    explained_variance   | 0.89         |
|    learning_rate        | 0.0003       |
|    loss                 | 11.6         |
|    n_updates            | 200          |
|    policy_gradient_loss | -0.00099     |
|    std                  | 1.02         |
|    value_loss           | 39.2         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 808          |
|    ep_rew_mean          | -241         |
| time/                   |              |
|    fps                  | 842          |
|    iterations           | 22           |
|    time_elapsed         | 106          |
|    total_timesteps      | 90112        |
| train/                  |              |
|    approx_kl            | 0.0011241701 |
|    clip_fraction        | 0.00708      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.905        |
|    learning_rate        | 0.0003       |
|    loss                 | 20.6         |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.000697    |
|    std                  | 0.99         |
|    value_loss           | 27           |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 831          |
|    ep_rew_mean          | -243         |
| time/                   |              |
|    fps                  | 839          |
|    iterations           | 23           |
|    time_elapsed         | 112          |
|    total_timesteps      | 94208        |
| train/                  |              |
|    approx_kl            | 0.0038545672 |
|    clip_fraction        | 0.0312       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.41        |
|    explained_variance   | 0.96         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.52         |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.00313     |
|    std                  | 0.986        |
|    value_loss           | 4.47         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 728         |
|    ep_rew_mean          | -234        |
| time/                   |             |
|    fps                  | 837         |
|    iterations           | 24          |
|    time_elapsed         | 117         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.003538526 |
|    clip_fraction        | 0.0378      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.41       |
|    explained_variance   | 0.831       |
|    learning_rate        | 0.0003      |
|    loss                 | 17.2        |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.00417    |
|    std                  | 0.996       |
|    value_loss           | 77          |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 736          |
|    ep_rew_mean          | -231         |
| time/                   |              |
|    fps                  | 835          |
|    iterations           | 25           |
|    time_elapsed         | 122          |
|    total_timesteps      | 102400       |
| train/                  |              |
|    approx_kl            | 0.0020497749 |
|    clip_fraction        | 0.00969      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.912        |
|    learning_rate        | 0.0003       |
|    loss                 | 7.52         |
|    n_updates            | 240          |
|    policy_gradient_loss | -0.000228    |
|    std                  | 1.01         |
|    value_loss           | 46.6         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 598         |
|    ep_rew_mean          | -225        |
| time/                   |             |
|    fps                  | 832         |
|    iterations           | 26          |
|    time_elapsed         | 127         |
|    total_timesteps      | 106496      |
| train/                  |             |
|    approx_kl            | 0.006263586 |
|    clip_fraction        | 0.0601      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.42       |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 22.5        |
|    n_updates            | 250         |
|    policy_gradient_loss | -0.00412    |
|    std                  | 0.998       |
|    value_loss           | 51.1        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 601          |
|    ep_rew_mean          | -226         |
| time/                   |              |
|    fps                  | 830          |
|    iterations           | 27           |
|    time_elapsed         | 133          |
|    total_timesteps      | 110592       |
| train/                  |              |
|    approx_kl            | 0.0013436625 |
|    clip_fraction        | 0.00518      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.911        |
|    learning_rate        | 0.0003       |
|    loss                 | 18.5         |
|    n_updates            | 260          |
|    policy_gradient_loss | -2.23e-05    |
|    std                  | 1.01         |
|    value_loss           | 55.6         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 625          |
|    ep_rew_mean          | -228         |
| time/                   |              |
|    fps                  | 828          |
|    iterations           | 28           |
|    time_elapsed         | 138          |
|    total_timesteps      | 114688       |
| train/                  |              |
|    approx_kl            | 0.0033709288 |
|    clip_fraction        | 0.0326       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.45        |
|    explained_variance   | 0.956        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.45         |
|    n_updates            | 270          |
|    policy_gradient_loss | -0.00117     |
|    std                  | 1.04         |
|    value_loss           | 21.3         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 629         |
|    ep_rew_mean          | -229        |
| time/                   |             |
|    fps                  | 826         |
|    iterations           | 29          |
|    time_elapsed         | 143         |
|    total_timesteps      | 118784      |
| train/                  |             |
|    approx_kl            | 0.005419432 |
|    clip_fraction        | 0.0182      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.46       |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | 9.26        |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.00165    |
|    std                  | 1.04        |
|    value_loss           | 53          |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 640          |
|    ep_rew_mean          | -230         |
| time/                   |              |
|    fps                  | 825          |
|    iterations           | 30           |
|    time_elapsed         | 148          |
|    total_timesteps      | 122880       |
| train/                  |              |
|    approx_kl            | 0.0038466998 |
|    clip_fraction        | 0.0216       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.45        |
|    explained_variance   | 0.9          |
|    learning_rate        | 0.0003       |
|    loss                 | 11.5         |
|    n_updates            | 290          |
|    policy_gradient_loss | -0.000876    |
|    std                  | 1.04         |
|    value_loss           | 50.1         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 659          |
|    ep_rew_mean          | -232         |
| time/                   |              |
|    fps                  | 823          |
|    iterations           | 31           |
|    time_elapsed         | 154          |
|    total_timesteps      | 126976       |
| train/                  |              |
|    approx_kl            | 0.0039891712 |
|    clip_fraction        | 0.0203       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.46        |
|    explained_variance   | 0.953        |
|    learning_rate        | 0.0003       |
|    loss                 | 9.4          |
|    n_updates            | 300          |
|    policy_gradient_loss | -0.000837    |
|    std                  | 1.04         |
|    value_loss           | 19           |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 661          |
|    ep_rew_mean          | -232         |
| time/                   |              |
|    fps                  | 822          |
|    iterations           | 32           |
|    time_elapsed         | 159          |
|    total_timesteps      | 131072       |
| train/                  |              |
|    approx_kl            | 0.0028138107 |
|    clip_fraction        | 0.0325       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.46        |
|    explained_variance   | 0.941        |
|    learning_rate        | 0.0003       |
|    loss                 | 24.7         |
|    n_updates            | 310          |
|    policy_gradient_loss | -0.00071     |
|    std                  | 1.04         |
|    value_loss           | 42.3         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 611          |
|    ep_rew_mean          | -229         |
| time/                   |              |
|    fps                  | 820          |
|    iterations           | 33           |
|    time_elapsed         | 164          |
|    total_timesteps      | 135168       |
| train/                  |              |
|    approx_kl            | 0.0016458771 |
|    clip_fraction        | 0.00574      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.45        |
|    explained_variance   | 0.929        |
|    learning_rate        | 0.0003       |
|    loss                 | 53.3         |
|    n_updates            | 320          |
|    policy_gradient_loss | 1.21e-05     |
|    std                  | 1.03         |
|    value_loss           | 54.8         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 590          |
|    ep_rew_mean          | -231         |
| time/                   |              |
|    fps                  | 819          |
|    iterations           | 34           |
|    time_elapsed         | 169          |
|    total_timesteps      | 139264       |
| train/                  |              |
|    approx_kl            | 0.0046200077 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.44        |
|    explained_variance   | 0.905        |
|    learning_rate        | 0.0003       |
|    loss                 | 9.75         |
|    n_updates            | 330          |
|    policy_gradient_loss | -0.000907    |
|    std                  | 1.02         |
|    value_loss           | 73.6         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 545          |
|    ep_rew_mean          | -230         |
| time/                   |              |
|    fps                  | 818          |
|    iterations           | 35           |
|    time_elapsed         | 175          |
|    total_timesteps      | 143360       |
| train/                  |              |
|    approx_kl            | 0.0027947808 |
|    clip_fraction        | 0.0179       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.44        |
|    explained_variance   | 0.939        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.24         |
|    n_updates            | 340          |
|    policy_gradient_loss | -0.000637    |
|    std                  | 1.01         |
|    value_loss           | 17.6         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 518          |
|    ep_rew_mean          | -228         |
| time/                   |              |
|    fps                  | 817          |
|    iterations           | 36           |
|    time_elapsed         | 180          |
|    total_timesteps      | 147456       |
| train/                  |              |
|    approx_kl            | 0.0022932815 |
|    clip_fraction        | 0.0219       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.43        |
|    explained_variance   | 0.937        |
|    learning_rate        | 0.0003       |
|    loss                 | 75           |
|    n_updates            | 350          |
|    policy_gradient_loss | -0.000402    |
|    std                  | 1.01         |
|    value_loss           | 50.9         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 545          |
|    ep_rew_mean          | -229         |
| time/                   |              |
|    fps                  | 816          |
|    iterations           | 37           |
|    time_elapsed         | 185          |
|    total_timesteps      | 151552       |
| train/                  |              |
|    approx_kl            | 0.0010380037 |
|    clip_fraction        | 0.00815      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.945        |
|    learning_rate        | 0.0003       |
|    loss                 | 5.78         |
|    n_updates            | 360          |
|    policy_gradient_loss | 9.08e-05     |
|    std                  | 0.991        |
|    value_loss           | 28           |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 528          |
|    ep_rew_mean          | -230         |
| time/                   |              |
|    fps                  | 815          |
|    iterations           | 38           |
|    time_elapsed         | 190          |
|    total_timesteps      | 155648       |
| train/                  |              |
|    approx_kl            | 0.0027591018 |
|    clip_fraction        | 0.0142       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.971        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.33         |
|    n_updates            | 370          |
|    policy_gradient_loss | -0.000762    |
|    std                  | 1            |
|    value_loss           | 14.2         |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 545        |
|    ep_rew_mean          | -230       |
| time/                   |            |
|    fps                  | 814        |
|    iterations           | 39         |
|    time_elapsed         | 196        |
|    total_timesteps      | 159744     |
| train/                  |            |
|    approx_kl            | 0.00332996 |
|    clip_fraction        | 0.0376     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.42      |
|    explained_variance   | 0.973      |
|    learning_rate        | 0.0003     |
|    loss                 | 2.9        |
|    n_updates            | 380        |
|    policy_gradient_loss | -0.00417   |
|    std                  | 0.994      |

In [ ]:
# Evaluate and capture average episode length and rewards over 20 episodes and save the results in a metrics directory as a csv file with the training time in seconds, mean reward, std reward, mean episode timesteps, and std episode timesteps.
# Also print these metrics to the console.
episode_rewards, episode_lengths = evaluate_policy(
    model,
    eval_env,
    n_eval_episodes=20,
    deterministic=True,
    return_episode_rewards=True,
)

mean_reward = sum(episode_rewards) / len(episode_rewards)
std_reward = pd.Series(episode_rewards).std()

mean_episode_timesteps = sum(episode_lengths) / len(episode_lengths)
std_episode_timesteps = pd.Series(episode_lengths).std()

print("Mean reward:", mean_reward)
print("Std reward:", std_reward)
print("Mean episode timesteps:", mean_episode_timesteps)
print("Std episode timesteps:", std_episode_timesteps)
print("Training time seconds:", training_time_seconds)

Mean reward: 369.24337660000003
Std reward: 3.8898725163329377
Mean episode timesteps: 1123.55
Std episode timesteps: 40.190958658568185
Training time seconds: 1220.4390835762024

In [ ]:
# Save the base model
model_path = f"{models_dir}/ppo_base_1M"
model.save(model_path)

print(f"Saved model to: {model_path}.zip")

Saved model to: models/ppo/base/ppo_base_1M.zip

In [ ]:
# Save metrics
metrics = pd.DataFrame([{
    "env_id": ENV_ID,
    "model": "PPO",
    "training_timesteps": 1_000_000,
    "n_eval_episodes": 20,
    "mean_reward": mean_reward,
    "std_reward": std_reward,
    "mean_episode_timesteps": mean_episode_timesteps,
    "std_episode_timesteps": std_episode_timesteps,
    "training_time_seconds": training_time_seconds,
}])

metrics_path = f"{metrics_dir}/ppo_base_metrics.csv"

if os.path.exists(metrics_path):
    old = pd.read_csv(metrics_path)
    metrics = pd.concat([old, metrics], ignore_index=True)

metrics.to_csv(metrics_path, index=False)
metrics

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,env_id,model,training_timesteps,n_eval_episodes,mean_reward,std_reward,mean_episode_timesteps,std_episode_timesteps,training_time_seconds
0,SailboatDiscrete-v0,PPO,100000,20,-199.105619,58.076113,452.15,452.323973,247.131226
1,Sailboat-v0,PPO,100000,20,369.243377,3.889873,1123.55,40.190959,1220.439084
2,Sailboat-v0,PPO,1000000,20,369.243377,3.889873,1123.55,40.190959,1220.439084

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Record video an evaluation episode of the trained model and save it in the videos directory with a name prefix of ppo_base_trained. The video should be saved as a mp4 file and should be named ppo_base_trained_episode_0.mp4.
video_env = gym.make(ENV_ID, render_mode="rgb_array")
video_env = RecordVideo(
    video_env,
    video_folder=videos_dir,
    name_prefix="ppo_base_trained",
    episode_trigger=lambda episode_id: episode_id == 0,
)

obs, info = video_env.reset()
done = False
truncated = False

while not (done or truncated):
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, done, truncated, info = video_env.step(action)

import builtins # imported to fix bug with recording video
builtins.quit = lambda *args, **kwargs: None # imported to fix bug with recording video
video_env.close()

/usr/local/lib/python3.12/dist-packages/gymnasium/wrappers/rendering.py:293: UserWarning: WARN: Overwriting existing videos at /content/drive/MyDrive/tiny_tackers/videos/ppo/base folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/moviepy/config_defaults.py:47: SyntaxWarning: invalid escape sequence '\P'
  IMAGEMAGICK_BINARY = r"C:\Program Files\ImageMagick-6.8.8-Q16\magick.exe"
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

- - - - - - - - - - - - - - - - - - - -
# Transfer Learning Step 1
## Train the base model to round a windward buoy and move to the next target
- Windward Buoy
- Reach Buoy
- - - - - - - - - - - - - - - - - - - -

In [1]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
# Confirm my repo location
%cd "/content/drive/My Drive/tiny_tackers"
!pwd

/content/drive/My Drive/tiny_tackers
/content/drive/My Drive/tiny_tackers

In [3]:
# Install Stable Baselines3 library if not already installed
!pip install stable-baselines3 gymnasium pygame

Requirement already satisfied: stable-baselines3 in /usr/local/lib/python3.12/dist-packages (2.8.0)
Requirement already satisfied: gymnasium in /usr/local/lib/python3.12/dist-packages (1.2.3)
Requirement already satisfied: pygame in /usr/local/lib/python3.12/dist-packages (2.6.1)
Requirement already satisfied: numpy<3.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.0.2)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.10.0+cu128)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (3.1.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (3.10.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (0.0.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3.0,>=2.3->stable-baselines3) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3.0,>=2.3->stable-baselines3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3.0,>=2.3->stable-baselines3) (3.0.3)

In [4]:
# Confirm necessary libraries and imports are installed if they weren't already
import os
import sys
import time
import pandas as pd
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_vec_env
from gymnasium.wrappers import RecordVideo

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [5]:
# Set Path to the Race Environment
RACE_ENV_PATH = "/content/drive/My Drive/tiny_tackers/gym_sailing_environments/gym_sailing_race"
sys.path.append(RACE_ENV_PATH)

In [6]:
# Import race environment and ensure it's coming from the correct path. Ending in tiny_tackers/gym_sailing_environments/gym_sailing_race/gym_sail_race/__init__.py
import gym_sail_race
print(gym_sail_race.__file__)

/content/drive/My Drive/tiny_tackers/gym_sailing_environments/gym_sailing_race/gym_sail_race/__init__.py

In [7]:
# Specify that the environment is going to be one where continuous actions are possible and it's the 2 mark race objective
ENV_ID = "SailboatRace2Mark-v0"

In [8]:
# Make folders for outcomes if folders do not already exist. Define new paths so we don't overwrite base model results or zip file
models_dir = "models/ppo/base_to_2mark_race"
videos_dir = "videos/ppo/base_to_2mark_race"
metrics_dir = "metrics"

os.makedirs(models_dir, exist_ok=True)
os.makedirs(videos_dir, exist_ok=True)
os.makedirs(metrics_dir, exist_ok=True)

In [9]:
# Make and define training and evaluation environments (render mode is none because vizualizing significantly slows down training and evaluation)
def make_env(render_mode=None):
    env = gym.make(
        ENV_ID,
        render_mode=render_mode,
    )
    env = Monitor(env)
    return env

In [10]:
# Improve efficiency with parallel environments in training and make train env
from stable_baselines3.common.env_util import make_vec_env
train_env = make_vec_env(lambda: make_env(), n_envs=4)

/usr/local/lib/python3.12/dist-packages/pygame/pkgdata.py:25: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import resource_stream, resource_exists
/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [11]:
# Make eval environment
eval_env = make_env()

In [12]:
# Load the base model if you completed base model training from the steps above
model = PPO.load("models/ppo/base/ppo_base_1M.zip", env=train_env)

/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [13]:
# Train the base model for an additional 1M steps in the race environment, where it needs to hit 2 marks
start = time.time()

model.learn(
    total_timesteps=1_000_000,
    progress_bar=True,
)

training_time_seconds = time.time() - start

Output()

/usr/local/lib/python3.12/dist-packages/ipywidgets/widgets/widget_output.py:111: DeprecationWarning:
Kernel._parent_header is deprecated in ipykernel 6. Use .get_parent()
  if ip and hasattr(ip, 'kernel') and hasattr(ip.kernel, '_parent_header'):

Streaming output truncated to the last 5000 lines.
|    loss                 | 5.4         |
|    n_updates            | 2620        |
|    policy_gradient_loss | -0.00174    |
|    std                  | 0.392       |
|    value_loss           | 18.1        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.43e+03    |
|    ep_rew_mean          | -93.6       |
| time/                   |             |
|    fps                  | 795         |
|    iterations           | 19          |
|    time_elapsed         | 97          |
|    total_timesteps      | 77824       |
| train/                  |             |
|    approx_kl            | 0.011700388 |
|    clip_fraction        | 0.0988      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.469      |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.8         |
|    n_updates            | 2630        |
|    policy_gradient_loss | 0.00217     |
|    std                  | 0.382       |
|    value_loss           | 16.8        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -88.2       |
| time/                   |             |
|    fps                  | 793         |
|    iterations           | 20          |
|    time_elapsed         | 103         |
|    total_timesteps      | 81920       |
| train/                  |             |
|    approx_kl            | 0.024208646 |
|    clip_fraction        | 0.121       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.46       |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.963       |
|    n_updates            | 2640        |
|    policy_gradient_loss | 0.00191     |
|    std                  | 0.384       |
|    value_loss           | 11.7        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.45e+03     |
|    ep_rew_mean          | -85.5        |
| time/                   |              |
|    fps                  | 792          |
|    iterations           | 21           |
|    time_elapsed         | 108          |
|    total_timesteps      | 86016        |
| train/                  |              |
|    approx_kl            | 0.0053166416 |
|    clip_fraction        | 0.0871       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.463       |
|    explained_variance   | 0.967        |
|    learning_rate        | 0.0003       |
|    loss                 | 4.57         |
|    n_updates            | 2650         |
|    policy_gradient_loss | 0.00152      |
|    std                  | 0.385        |
|    value_loss           | 11.5         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.48e+03    |
|    ep_rew_mean          | -84.4       |
| time/                   |             |
|    fps                  | 791         |
|    iterations           | 22          |
|    time_elapsed         | 113         |
|    total_timesteps      | 90112       |
| train/                  |             |
|    approx_kl            | 0.007139885 |
|    clip_fraction        | 0.0886      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.462      |
|    explained_variance   | 0.957       |
|    learning_rate        | 0.0003      |
|    loss                 | 10.5        |
|    n_updates            | 2660        |
|    policy_gradient_loss | 0.00101     |
|    std                  | 0.383       |
|    value_loss           | 16          |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.5e+03     |
|    ep_rew_mean          | -82.7       |
| time/                   |             |
|    fps                  | 790         |
|    iterations           | 23          |
|    time_elapsed         | 119         |
|    total_timesteps      | 94208       |
| train/                  |             |
|    approx_kl            | 0.009428836 |
|    clip_fraction        | 0.0792      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.464      |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.764       |
|    n_updates            | 2670        |
|    policy_gradient_loss | -0.00167    |
|    std                  | 0.387       |
|    value_loss           | 9.76        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.52e+03    |
|    ep_rew_mean          | -75.2       |
| time/                   |             |
|    fps                  | 790         |
|    iterations           | 24          |
|    time_elapsed         | 124         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.012463959 |
|    clip_fraction        | 0.0921      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.473      |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.814       |
|    n_updates            | 2680        |
|    policy_gradient_loss | 0.00215     |
|    std                  | 0.389       |
|    value_loss           | 7.61        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.52e+03     |
|    ep_rew_mean          | -75.2        |
| time/                   |              |
|    fps                  | 789          |
|    iterations           | 25           |
|    time_elapsed         | 129          |
|    total_timesteps      | 102400       |
| train/                  |              |
|    approx_kl            | 0.0065795714 |
|    clip_fraction        | 0.0763       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.473       |
|    explained_variance   | 0.957        |
|    learning_rate        | 0.0003       |
|    loss                 | 13.1         |
|    n_updates            | 2690         |
|    policy_gradient_loss | -0.00281     |
|    std                  | 0.389        |
|    value_loss           | 20.2         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.54e+03     |
|    ep_rew_mean          | -73.3        |
| time/                   |              |
|    fps                  | 788          |
|    iterations           | 26           |
|    time_elapsed         | 135          |
|    total_timesteps      | 106496       |
| train/                  |              |
|    approx_kl            | 0.0079106465 |
|    clip_fraction        | 0.0813       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.475       |
|    explained_variance   | 0.97         |
|    learning_rate        | 0.0003       |
|    loss                 | 1.03         |
|    n_updates            | 2700         |
|    policy_gradient_loss | 0.000147     |
|    std                  | 0.392        |
|    value_loss           | 6.21         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.54e+03    |
|    ep_rew_mean          | -73.3       |
| time/                   |             |
|    fps                  | 787         |
|    iterations           | 27          |
|    time_elapsed         | 140         |
|    total_timesteps      | 110592      |
| train/                  |             |
|    approx_kl            | 0.003143161 |
|    clip_fraction        | 0.0766      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.482      |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.95        |
|    n_updates            | 2710        |
|    policy_gradient_loss | 0.00187     |
|    std                  | 0.391       |
|    value_loss           | 25.7        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.55e+03    |
|    ep_rew_mean          | -70.2       |
| time/                   |             |
|    fps                  | 786         |
|    iterations           | 28          |
|    time_elapsed         | 145         |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.007987052 |
|    clip_fraction        | 0.107       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.488      |
|    explained_variance   | 0.988       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.519       |
|    n_updates            | 2720        |
|    policy_gradient_loss | 0.00333     |
|    std                  | 0.396       |
|    value_loss           | 4.04        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.56e+03     |
|    ep_rew_mean          | -68.9        |
| time/                   |              |
|    fps                  | 785          |
|    iterations           | 29           |
|    time_elapsed         | 151          |
|    total_timesteps      | 118784       |
| train/                  |              |
|    approx_kl            | 0.0039990526 |
|    clip_fraction        | 0.0409       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.491       |
|    explained_variance   | 0.961        |
|    learning_rate        | 0.0003       |
|    loss                 | 55.1         |
|    n_updates            | 2730         |
|    policy_gradient_loss | 0.000928     |
|    std                  | 0.393        |
|    value_loss           | 20.5         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.58e+03     |
|    ep_rew_mean          | -65.1        |
| time/                   |              |
|    fps                  | 784          |
|    iterations           | 30           |
|    time_elapsed         | 156          |
|    total_timesteps      | 122880       |
| train/                  |              |
|    approx_kl            | 0.0051645604 |
|    clip_fraction        | 0.0815       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.49        |
|    explained_variance   | 0.986        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.868        |
|    n_updates            | 2740         |
|    policy_gradient_loss | 0.000387     |
|    std                  | 0.396        |
|    value_loss           | 8.62         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.6e+03      |
|    ep_rew_mean          | -61.3        |
| time/                   |              |
|    fps                  | 784          |
|    iterations           | 31           |
|    time_elapsed         | 161          |
|    total_timesteps      | 126976       |
| train/                  |              |
|    approx_kl            | 0.0039546355 |
|    clip_fraction        | 0.0778       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.494       |
|    explained_variance   | 0.978        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.58         |
|    n_updates            | 2750         |
|    policy_gradient_loss | -0.000443    |
|    std                  | 0.398        |
|    value_loss           | 11.2         |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.61e+03   |
|    ep_rew_mean          | -57.8      |
| time/                   |            |
|    fps                  | 783        |
|    iterations           | 32         |
|    time_elapsed         | 167        |
|    total_timesteps      | 131072     |
| train/                  |            |
|    approx_kl            | 0.00902788 |
|    clip_fraction        | 0.101      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.5       |
|    explained_variance   | 0.99       |
|    learning_rate        | 0.0003     |
|    loss                 | 0.84       |
|    n_updates            | 2760       |
|    policy_gradient_loss | 0.00145    |
|    std                  | 0.4        |
|    value_loss           | 5.72       |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.62e+03     |
|    ep_rew_mean          | -54          |
| time/                   |              |
|    fps                  | 783          |
|    iterations           | 33           |
|    time_elapsed         | 172          |
|    total_timesteps      | 135168       |
| train/                  |              |
|    approx_kl            | 0.0054365597 |
|    clip_fraction        | 0.0735       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.508       |
|    explained_variance   | 0.988        |
|    learning_rate        | 0.0003       |
|    loss                 | 22.2         |
|    n_updates            | 2770         |
|    policy_gradient_loss | 0.000721     |
|    std                  | 0.404        |
|    value_loss           | 9.54         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.62e+03    |
|    ep_rew_mean          | -54         |
| time/                   |             |
|    fps                  | 782         |
|    iterations           | 34          |
|    time_elapsed         | 178         |
|    total_timesteps      | 139264      |
| train/                  |             |
|    approx_kl            | 0.006810153 |
|    clip_fraction        | 0.0674      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.509      |
|    explained_variance   | 0.985       |
|    learning_rate        | 0.0003      |
|    loss                 | 20.8        |
|    n_updates            | 2780        |
|    policy_gradient_loss | 0.0011      |
|    std                  | 0.402       |
|    value_loss           | 9.99        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.64e+03    |
|    ep_rew_mean          | -50.1       |
| time/                   |             |
|    fps                  | 782         |
|    iterations           | 35          |
|    time_elapsed         | 183         |
|    total_timesteps      | 143360      |
| train/                  |             |
|    approx_kl            | 0.016556863 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.497      |
|    explained_variance   | 0.995       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.151       |
|    n_updates            | 2790        |
|    policy_gradient_loss | 0.00257     |
|    std                  | 0.396       |
|    value_loss           | 2.89        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.64e+03     |
|    ep_rew_mean          | -50.1        |
| time/                   |              |
|    fps                  | 781          |
|    iterations           | 36           |
|    time_elapsed         | 188          |
|    total_timesteps      | 147456       |
| train/                  |              |
|    approx_kl            | 0.0037351884 |
|    clip_fraction        | 0.0266       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.495       |
|    explained_variance   | 0.981        |
|    learning_rate        | 0.0003       |
|    loss                 | 2.52         |
|    n_updates            | 2800         |
|    policy_gradient_loss | 3.06e-05     |
|    std                  | 0.397        |
|    value_loss           | 13.5         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.66e+03    |
|    ep_rew_mean          | -49.3       |
| time/                   |             |
|    fps                  | 781         |
|    iterations           | 37          |
|    time_elapsed         | 193         |
|    total_timesteps      | 151552      |
| train/                  |             |
|    approx_kl            | 0.005320102 |
|    clip_fraction        | 0.0589      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.488      |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.984       |
|    n_updates            | 2810        |
|    policy_gradient_loss | 0.000221    |
|    std                  | 0.393       |
|    value_loss           | 4.84        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.66e+03     |
|    ep_rew_mean          | -49.3        |
| time/                   |              |
|    fps                  | 780          |
|    iterations           | 38           |
|    time_elapsed         | 199          |
|    total_timesteps      | 155648       |
| train/                  |              |
|    approx_kl            | 0.0037691928 |
|    clip_fraction        | 0.0261       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.483       |
|    explained_variance   | 0.934        |
|    learning_rate        | 0.0003       |
|    loss                 | 11.8         |
|    n_updates            | 2820         |
|    policy_gradient_loss | 0.000327     |
|    std                  | 0.391        |
|    value_loss           | 23.4         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.67e+03    |
|    ep_rew_mean          | -48.6       |
| time/                   |             |
|    fps                  | 780         |
|    iterations           | 39          |
|    time_elapsed         | 204         |
|    total_timesteps      | 159744      |
| train/                  |             |
|    approx_kl            | 0.006936365 |
|    clip_fraction        | 0.0705      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.463      |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.545       |
|    n_updates            | 2830        |
|    policy_gradient_loss | 0.000376    |
|    std                  | 0.379       |
|    value_loss           | 4.33        |
-----------------------------------------
------------------------------------------
| rollout/                |              |

In [14]:
# Evaluate and capture average episode length and rewards over 20 episodes and save the results in a metrics directory as a csv file with the training time in seconds, mean reward, std reward, mean episode timesteps, and std episode timesteps.
# Also print these metrics to the console.
episode_rewards, episode_lengths = evaluate_policy(
    model,
    eval_env,
    n_eval_episodes=20,
    deterministic=True,
    return_episode_rewards=True,
)

mean_reward = sum(episode_rewards) / len(episode_rewards)
std_reward = pd.Series(episode_rewards).std()

mean_episode_timesteps = sum(episode_lengths) / len(episode_lengths)
std_episode_timesteps = pd.Series(episode_lengths).std()

print("Mean reward:", mean_reward)
print("Std reward:", std_reward)
print("Mean episode timesteps:", mean_episode_timesteps)
print("Std episode timesteps:", std_episode_timesteps)
print("Training time seconds:", training_time_seconds)

Mean reward: 556.1588681000001
Std reward: 87.17929409245636
Mean episode timesteps: 1287.1
Std episode timesteps: 45.16857314549574
Training time seconds: 1303.0308735370636

In [15]:
# Save the base to 2mark race model
model_path = f"{models_dir}/ppo_base_to_2mark_race_2M"
model.save(model_path)
print(f"Saved model to: {model_path}.zip")

Saved model to: models/ppo/base_to_2mark_race/ppo_base_to_2mark_race_2M.zip

In [16]:
# Save metrics
metrics = pd.DataFrame([{
    "env_id": ENV_ID,
    "model": "PPO",
    "source_model": "models/ppo/base/ppo_base_1M.zip",
    "training_stage": "base_to_race",
    "additional_training_timesteps": 500_000,
    "n_eval_episodes": 20,
    "mean_reward": mean_reward,
    "std_reward": std_reward,
    "mean_episode_timesteps": mean_episode_timesteps,
    "std_episode_timesteps": std_episode_timesteps,
    "training_time_seconds": training_time_seconds,
}])

metrics_path = f"{metrics_dir}/ppo_base_to_2mark_race_metrics.csv"

if os.path.exists(metrics_path):
    old = pd.read_csv(metrics_path)
    metrics = pd.concat([old, metrics], ignore_index=True)

metrics.to_csv(metrics_path, index=False)
metrics

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,env_id,model,source_model,training_stage,additional_training_timesteps,n_eval_episodes,mean_reward,std_reward,mean_episode_timesteps,std_episode_timesteps,training_time_seconds
0,SailboatRace-v0,PPO,models/ppo/base/ppo_base_1M.zip,base_to_race,500000,20,-4725.640139,NaN,20000.0,NaN,644.248418
1,SailboatRace2Mark-v0,PPO,models/ppo/base/ppo_base_1M.zip,base_to_race,500000,20,-105.396178,NaN,2607.0,NaN,662.536380
2,SailboatRace2Mark-v0,PPO,models/ppo/base/ppo_base_1M.zip,base_to_race,500000,20,556.158868,87.179294,1287.1,45.168573,1303.030874

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [17]:
# Record video an evaluation episode of the trained model and save it in the videos directory with a name prefix of ppo_base_trained. The video should be saved as a mp4 file and should be named ppo_base_trained_episode_0.mp4.

# Ensure that we are recording a video with the environment that only has two marks to go to
video_env = gym.make(
    ENV_ID,
    render_mode="rgb_array",
)

video_env = RecordVideo(
    video_env,
    video_folder=videos_dir,
    name_prefix="ppo_base_to_2mark_race_trained",
    episode_trigger=lambda episode_id: episode_id == 0,
)

obs, info = video_env.reset()
done = False
truncated = False

while not (done or truncated):
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, done, truncated, info = video_env.step(action)

import builtins # imported to fix bug with recording video
builtins.quit = lambda *args, **kwargs: None # imported to fix bug with recording video
video_env.close()

/usr/local/lib/python3.12/dist-packages/gymnasium/wrappers/rendering.py:293: UserWarning: WARN: Overwriting existing videos at /content/drive/MyDrive/tiny_tackers/videos/ppo/base_to_2mark_race folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

- - - - - - - - - - - - - - - - - - - - - - - -
# Transfer Learning Step 2
## Training the base to race model on the full Race Environment

- Windward Buoy
- Reach Buoy
- Leeward Buoy
- Windward Buoy
- Leeward Buoy
- Windward Buoy
- - - - - - - - - - - - - - - - - - - - - - - -

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Confirm my repo location
%cd "/content/drive/My Drive/tiny_tackers"
!pwd

/content/drive/My Drive/tiny_tackers
/content/drive/My Drive/tiny_tackers

In [ ]:
# Install Stable Baselines3 library if not already installed
!pip install stable-baselines3 gymnasium pygame

Requirement already satisfied: stable-baselines3 in /usr/local/lib/python3.12/dist-packages (2.8.0)
Requirement already satisfied: gymnasium in /usr/local/lib/python3.12/dist-packages (1.2.3)
Requirement already satisfied: pygame in /usr/local/lib/python3.12/dist-packages (2.6.1)
Requirement already satisfied: numpy<3.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.0.2)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.10.0+cu128)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (3.1.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from stable-baselines3) (3.10.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (0.0.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3.0,>=2.3->stable-baselines3) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3.0,>=2.3->stable-baselines3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3.0,>=2.3->stable-baselines3) (3.0.3)

In [ ]:
# Confirm necessary libraries and imports are installed if they weren't already
import os
import sys
import time
import pandas as pd
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_vec_env
from gymnasium.wrappers import RecordVideo

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# Set Path to the Race Environment
RACE_ENV_PATH = "/content/drive/My Drive/tiny_tackers/gym_sailing_environments/gym_sailing_race"
sys.path.append(RACE_ENV_PATH)

In [ ]:
# Import race environment and ensure it's coming from the correct path. Ending in tiny_tackers/gym_sailing_environments/gym_sailing_race/gym_sail_race/__init__.py
import gym_sail_race
print(gym_sail_race.__file__)

/content/drive/My Drive/tiny_tackers/gym_sailing_environments/gym_sailing_race/gym_sail_race/__init__.py

In [ ]:
# Specifify that the environment is going to be one where continuous actions are possible and it's the race objective
ENV_ID = "SailboatRace-v0"

In [ ]:
# Test that we can run the environment
test_env = gym.make(ENV_ID)
obs, info = test_env.reset()
print("Observation:", obs)
print("Observation space:", test_env.observation_space)
print("Action space:", test_env.action_space)
action = test_env.action_space.sample()
obs, reward, terminated, truncated, info = test_env.step(action)
print("Step worked")
print("Reward:", reward)
print("Terminated:", terminated)
print("Truncated:", truncated)
test_env.close()

/usr/local/lib/python3.12/dist-packages/pygame/pkgdata.py:25: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import resource_stream, resource_exists
/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Observation: [ 0.         -0.19522105  0.          0.10705367  1.27899765]
Observation space: Box([-10.          -3.14159265  -1.          -3.14159265   0.        ], [ 10.           3.14159265   1.           3.14159265 100.        ], (5,), float64)
Action space: Box(-1.0, 1.0, (1,), float64)
Step worked
Reward: -0.11051600424876398
Terminated: False
Truncated: False

In [ ]:
# Make folders for outcomes if folders do not already exist. Define new paths so we don't overwrite base model results or zip file
models_dir = "models/ppo/race"
videos_dir = "videos/ppo/race"
metrics_dir = "metrics"

os.makedirs(models_dir, exist_ok=True)
os.makedirs(videos_dir, exist_ok=True)
os.makedirs(metrics_dir, exist_ok=True)

In [ ]:
# Make and define training and evaluation environments (render mode is none because vizualizing significantly slows down training and evaluation)
def make_env(render_mode=None):
    env = gym.make(ENV_ID, render_mode=render_mode)
    env = Monitor(env)
    return env

train_env = make_env()
eval_env = make_env()

In [ ]:
# Improve efficiency with parallel environments
from stable_baselines3.common.env_util import make_vec_env
train_env = make_vec_env(lambda: make_env(), n_envs=4)

In [ ]:
# Train PPO for 1_000_000 timesteps and save the training time in seconds
model = PPO(
    policy="MlpPolicy",
    env=train_env,
    learning_rate=3e-4,
    n_steps=1024,
    batch_size=64,
    gamma=0.99,
    verbose=1,
)

start = time.time()
model.learn(
    total_timesteps=1_000_000,
    progress_bar=True,
)

training_time_seconds = time.time() - start

Using cuda device

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning:
datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects
to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Output()

/usr/local/lib/python3.12/dist-packages/ipywidgets/widgets/widget_output.py:111: DeprecationWarning:
Kernel._parent_header is deprecated in ipykernel 6. Use .get_parent()
  if ip and hasattr(ip, 'kernel') and hasattr(ip.kernel, '_parent_header'):

/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(

Streaming output truncated to the last 5000 lines.
|    loss                 | 2.77        |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00122    |
|    std                  | 0.945       |
|    value_loss           | 12.9        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.32e+03    |
|    ep_rew_mean          | -381        |
| time/                   |             |
|    fps                  | 774         |
|    iterations           | 19          |
|    time_elapsed         | 100         |
|    total_timesteps      | 77824       |
| train/                  |             |
|    approx_kl            | 0.002879901 |
|    clip_fraction        | 0.0074      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.36       |
|    explained_variance   | 0.871       |
|    learning_rate        | 0.0003      |
|    loss                 | 13.7        |
|    n_updates            | 180         |
|    policy_gradient_loss | 0.000106    |
|    std                  | 0.939       |
|    value_loss           | 27          |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.34e+03    |
|    ep_rew_mean          | -382        |
| time/                   |             |
|    fps                  | 773         |
|    iterations           | 20          |
|    time_elapsed         | 105         |
|    total_timesteps      | 81920       |
| train/                  |             |
|    approx_kl            | 0.005401431 |
|    clip_fraction        | 0.0346      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.35       |
|    explained_variance   | 0.925       |
|    learning_rate        | 0.0003      |
|    loss                 | 2.65        |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.00168    |
|    std                  | 0.934       |
|    value_loss           | 17.5        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.34e+03    |
|    ep_rew_mean          | -381        |
| time/                   |             |
|    fps                  | 772         |
|    iterations           | 21          |
|    time_elapsed         | 111         |
|    total_timesteps      | 86016       |
| train/                  |             |
|    approx_kl            | 0.002187247 |
|    clip_fraction        | 0.0115      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.34       |
|    explained_variance   | 0.918       |
|    learning_rate        | 0.0003      |
|    loss                 | 4.81        |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.000207   |
|    std                  | 0.924       |
|    value_loss           | 23          |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.33e+03    |
|    ep_rew_mean          | -377        |
| time/                   |             |
|    fps                  | 771         |
|    iterations           | 22          |
|    time_elapsed         | 116         |
|    total_timesteps      | 90112       |
| train/                  |             |
|    approx_kl            | 0.001958487 |
|    clip_fraction        | 0.00959     |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.34       |
|    explained_variance   | 0.896       |
|    learning_rate        | 0.0003      |
|    loss                 | 62.6        |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.00124    |
|    std                  | 0.914       |
|    value_loss           | 39.1        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.32e+03     |
|    ep_rew_mean          | -375         |
| time/                   |              |
|    fps                  | 771          |
|    iterations           | 23           |
|    time_elapsed         | 122          |
|    total_timesteps      | 94208        |
| train/                  |              |
|    approx_kl            | 0.0070723435 |
|    clip_fraction        | 0.0452       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.32        |
|    explained_variance   | 0.886        |
|    learning_rate        | 0.0003       |
|    loss                 | 13.9         |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.00118     |
|    std                  | 0.904        |
|    value_loss           | 37.2         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.31e+03     |
|    ep_rew_mean          | -372         |
| time/                   |              |
|    fps                  | 770          |
|    iterations           | 24           |
|    time_elapsed         | 127          |
|    total_timesteps      | 98304        |
| train/                  |              |
|    approx_kl            | 0.0013227165 |
|    clip_fraction        | 0.0112       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.31        |
|    explained_variance   | 0.916        |
|    learning_rate        | 0.0003       |
|    loss                 | 43.7         |
|    n_updates            | 230          |
|    policy_gradient_loss | -0.000187    |
|    std                  | 0.892        |
|    value_loss           | 29           |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.31e+03     |
|    ep_rew_mean          | -369         |
| time/                   |              |
|    fps                  | 769          |
|    iterations           | 25           |
|    time_elapsed         | 133          |
|    total_timesteps      | 102400       |
| train/                  |              |
|    approx_kl            | 0.0033339509 |
|    clip_fraction        | 0.0236       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.29        |
|    explained_variance   | 0.893        |
|    learning_rate        | 0.0003       |
|    loss                 | 19.7         |
|    n_updates            | 240          |
|    policy_gradient_loss | -0.00173     |
|    std                  | 0.879        |
|    value_loss           | 35.1         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.3e+03      |
|    ep_rew_mean          | -366         |
| time/                   |              |
|    fps                  | 769          |
|    iterations           | 26           |
|    time_elapsed         | 138          |
|    total_timesteps      | 106496       |
| train/                  |              |
|    approx_kl            | 0.0024366588 |
|    clip_fraction        | 0.0222       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.28        |
|    explained_variance   | 0.905        |
|    learning_rate        | 0.0003       |
|    loss                 | 17.3         |
|    n_updates            | 250          |
|    policy_gradient_loss | 0.000652     |
|    std                  | 0.863        |
|    value_loss           | 29.7         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.29e+03     |
|    ep_rew_mean          | -364         |
| time/                   |              |
|    fps                  | 769          |
|    iterations           | 27           |
|    time_elapsed         | 143          |
|    total_timesteps      | 110592       |
| train/                  |              |
|    approx_kl            | 0.0014015386 |
|    clip_fraction        | 0.0197       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.27        |
|    explained_variance   | 0.919        |
|    learning_rate        | 0.0003       |
|    loss                 | 1.44         |
|    n_updates            | 260          |
|    policy_gradient_loss | -0.000562    |
|    std                  | 0.856        |
|    value_loss           | 27.1         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.29e+03     |
|    ep_rew_mean          | -362         |
| time/                   |              |
|    fps                  | 768          |
|    iterations           | 28           |
|    time_elapsed         | 149          |
|    total_timesteps      | 114688       |
| train/                  |              |
|    approx_kl            | 0.0060168747 |
|    clip_fraction        | 0.0221       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.26        |
|    explained_variance   | 0.907        |
|    learning_rate        | 0.0003       |
|    loss                 | 15.8         |
|    n_updates            | 270          |
|    policy_gradient_loss | -0.00073     |
|    std                  | 0.855        |
|    value_loss           | 32.7         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.28e+03     |
|    ep_rew_mean          | -359         |
| time/                   |              |
|    fps                  | 768          |
|    iterations           | 29           |
|    time_elapsed         | 154          |
|    total_timesteps      | 118784       |
| train/                  |              |
|    approx_kl            | 0.0028470834 |
|    clip_fraction        | 0.00906      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.27        |
|    explained_variance   | 0.904        |
|    learning_rate        | 0.0003       |
|    loss                 | 18.4         |
|    n_updates            | 280          |
|    policy_gradient_loss | 0.000415     |
|    std                  | 0.865        |
|    value_loss           | 32.9         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.28e+03     |
|    ep_rew_mean          | -358         |
| time/                   |              |
|    fps                  | 767          |
|    iterations           | 30           |
|    time_elapsed         | 160          |
|    total_timesteps      | 122880       |
| train/                  |              |
|    approx_kl            | 0.0023813369 |
|    clip_fraction        | 0.0126       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.27        |
|    explained_variance   | 0.846        |
|    learning_rate        | 0.0003       |
|    loss                 | 8.62         |
|    n_updates            | 290          |
|    policy_gradient_loss | -3.39e-05    |
|    std                  | 0.86         |
|    value_loss           | 39.8         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.27e+03    |
|    ep_rew_mean          | -356        |
| time/                   |             |
|    fps                  | 767         |
|    iterations           | 31          |
|    time_elapsed         | 165         |
|    total_timesteps      | 126976      |
| train/                  |             |
|    approx_kl            | 0.002909113 |
|    clip_fraction        | 0.0349      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.25       |
|    explained_variance   | 0.919       |
|    learning_rate        | 0.0003      |
|    loss                 | 10.5        |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.000224   |
|    std                  | 0.835       |
|    value_loss           | 24.9        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.28e+03     |
|    ep_rew_mean          | -357         |
| time/                   |              |
|    fps                  | 767          |
|    iterations           | 32           |
|    time_elapsed         | 170          |
|    total_timesteps      | 131072       |
| train/                  |              |
|    approx_kl            | 0.0015004058 |
|    clip_fraction        | 0.0183       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.23        |
|    explained_variance   | 0.888        |
|    learning_rate        | 0.0003       |
|    loss                 | 15           |
|    n_updates            | 310          |
|    policy_gradient_loss | 0.000279     |
|    std                  | 0.828        |
|    value_loss           | 30.8         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.31e+03     |
|    ep_rew_mean          | -360         |
| time/                   |              |
|    fps                  | 767          |
|    iterations           | 33           |
|    time_elapsed         | 176          |
|    total_timesteps      | 135168       |
| train/                  |              |
|    approx_kl            | 0.0043285424 |
|    clip_fraction        | 0.0418       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.23        |
|    explained_variance   | 0.93         |
|    learning_rate        | 0.0003       |
|    loss                 | 5.12         |
|    n_updates            | 320          |
|    policy_gradient_loss | -0.00326     |
|    std                  | 0.825        |
|    value_loss           | 21.2         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.33e+03     |
|    ep_rew_mean          | -362         |
| time/                   |              |
|    fps                  | 767          |
|    iterations           | 34           |
|    time_elapsed         | 181          |
|    total_timesteps      | 139264       |
| train/                  |              |
|    approx_kl            | 0.0023339656 |
|    clip_fraction        | 0.0119       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.22        |
|    explained_variance   | 0.936        |
|    learning_rate        | 0.0003       |
|    loss                 | 10.4         |
|    n_updates            | 330          |
|    policy_gradient_loss | 0.000757     |
|    std                  | 0.825        |
|    value_loss           | 19.1         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.36e+03     |
|    ep_rew_mean          | -364         |
| time/                   |              |
|    fps                  | 766          |
|    iterations           | 35           |
|    time_elapsed         | 186          |
|    total_timesteps      | 143360       |
| train/                  |              |
|    approx_kl            | 0.0057676546 |
|    clip_fraction        | 0.0401       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.22        |
|    explained_variance   | 0.939        |
|    learning_rate        | 0.0003       |
|    loss                 | 3.26         |
|    n_updates            | 340          |
|    policy_gradient_loss | 0.000375     |
|    std                  | 0.816        |
|    value_loss           | 19.8         |
------------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.34e+03   |
|    ep_rew_mean          | -362       |
| time/                   |            |
|    fps                  | 767        |
|    iterations           | 36         |
|    time_elapsed         | 192        |
|    total_timesteps      | 147456     |
| train/                  |            |
|    approx_kl            | 0.00320571 |
|    clip_fraction        | 0.0248     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.21      |
|    explained_variance   | 0.936      |
|    learning_rate        | 0.0003     |
|    loss                 | 3.26       |
|    n_updates            | 350        |
|    policy_gradient_loss | 0.000406   |
|    std                  | 0.817      |
|    value_loss           | 21.9       |
----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.31e+03     |
|    ep_rew_mean          | -355         |
| time/                   |              |
|    fps                  | 766          |
|    iterations           | 37           |
|    time_elapsed         | 197          |
|    total_timesteps      | 151552       |
| train/                  |              |
|    approx_kl            | 0.0021765297 |
|    clip_fraction        | 0.0243       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.21        |
|    explained_variance   | 0.926        |
|    learning_rate        | 0.0003       |
|    loss                 | 24.6         |
|    n_updates            | 360          |
|    policy_gradient_loss | -0.00107     |
|    std                  | 0.81         |
|    value_loss           | 22.4         |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.3e+03      |
|    ep_rew_mean          | -352         |
| time/                   |              |
|    fps                  | 766          |
|    iterations           | 38           |
|    time_elapsed         | 203          |
|    total_timesteps      | 155648       |
| train/                  |              |
|    approx_kl            | 0.0016800708 |
|    clip_fraction        | 0.0389       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.2         |
|    explained_variance   | 0.926        |
|    learning_rate        | 0.0003       |
|    loss                 | 10.5         |
|    n_updates            | 370          |
|    policy_gradient_loss | 0.000274     |
|    std                  | 0.808        |
|    value_loss           | 26.4         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.3e+03     |
|    ep_rew_mean          | -349        |
| time/                   |             |
|    fps                  | 766         |
|    iterations           | 39          |
|    time_elapsed         | 208         |
|    total_timesteps      | 159744      |
| train/                  |             |
|    approx_kl            | 0.007692809 |
|    clip_fraction        | 0.0242      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.2        |
|    explained_variance   | 0.934       |
|    learning_rate        | 0.0003      |
|    loss                 | 37.1        |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.000416   |
|    std                  | 0.805       |
|    value_loss           | 21.7        |
-----------------------------------------

In [ ]:
# Evaluate and capture average episode length and rewards over 20 episodes and save the results in a metrics directory as a csv file with the training time in seconds, mean reward, std reward, mean episode timesteps, and std episode timesteps.
# Also print these metrics to the console.
episode_rewards, episode_lengths = evaluate_policy(
    model,
    eval_env,
    n_eval_episodes=20,
    deterministic=True,
    return_episode_rewards=True,
)

mean_reward = sum(episode_rewards) / len(episode_rewards)
std_reward = pd.Series(episode_rewards).std()

mean_episode_timesteps = sum(episode_lengths) / len(episode_lengths)
std_episode_timesteps = pd.Series(episode_lengths).std()

print("Mean reward:", mean_reward)
print("Std reward:", std_reward)
print("Mean episode timesteps:", mean_episode_timesteps)
print("Std episode timesteps:", std_episode_timesteps)
print("Training time seconds:", training_time_seconds)

Mean reward: -309.696127
Std reward: 5.832011720969797e-14
Mean episode timesteps: 1130.0
Std episode timesteps: 0.0
Training time seconds: 1270.6828384399414

In [ ]:
# Save the RACE model
model_path = f"{models_dir}/ppo_race_1M"
model.save(model_path)

print(f"Saved model to: {model_path}.zip")

Saved model to: models/ppo/race/ppo_race_1M.zip

In [ ]:
# Save metrics
metrics = pd.DataFrame([{
    "env_id": ENV_ID,
    "model": "PPO",
    "training_timesteps": 1_000_000,
    "n_eval_episodes": 20,
    "mean_reward": mean_reward,
    "std_reward": std_reward,
    "mean_episode_timesteps": mean_episode_timesteps,
    "std_episode_timesteps": std_episode_timesteps,
    "training_time_seconds": training_time_seconds,
}])

metrics_path = f"{metrics_dir}/ppo_race_metrics.csv"

if os.path.exists(metrics_path):
    old = pd.read_csv(metrics_path)
    metrics = pd.concat([old, metrics], ignore_index=True)

metrics.to_csv(metrics_path, index=False)
metrics

NameError: name 'mean_reward' is not defined

In [ ]:
# Record video an evaluation episode of the trained model and save it in the videos directory with a name prefix of ppo_base_trained. The video should be saved as a mp4 file and should be named ppo_base_trained_episode_0.mp4.
video_env = gym.make(ENV_ID, render_mode="rgb_array")
video_env = RecordVideo(
    video_env,
    video_folder=videos_dir,
    name_prefix="ppo_race_trained",
    episode_trigger=lambda episode_id: episode_id == 0,
)

obs, info = video_env.reset()
done = False
truncated = False

while not (done or truncated):
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, done, truncated, info = video_env.step(action)

import builtins # imported to fix bug with recording video
builtins.quit = lambda *args, **kwargs: None # imported to fix bug with recording video
video_env.close()

/usr/local/lib/python3.12/dist-packages/gymnasium/wrappers/rendering.py:293: UserWarning: WARN: Overwriting existing videos at /content/drive/My Drive/tiny_tackers/videos/ppo/race folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(

NameError: name 'model' is not defined

In [ ]:
#Debugging

In [ ]:
video_env = gym.make(ENV_ID, render_mode="rgb_array")
obs, info = video_env.reset()

frame = video_env.render()

print(type(frame))
print(frame.shape)
print(frame.dtype)

video_env.close()

<class 'numpy.ndarray'>
(680, 680, 3)
uint8

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
env = gym.make(ENV_ID)

for i in range(5):
    obs, info = env.reset()
    print(f"Reset {i}")
    print("obs:", obs)
    print("info:", info)
    print()

env.close()

Reset 0
obs: [0.         0.19269012 0.         0.16656179 1.25410869]
info: {}

Reset 1
obs: [0.         0.18983249 0.         0.13700912 1.15626516]
info: {}

Reset 2
obs: [ 0.         -0.14745744  0.          0.12127385  1.19066536]
info: {}

Reset 3
obs: [0.         0.19071979 0.         0.14866379 1.21417877]
info: {}

Reset 4
obs: [ 0.         -0.17819893  0.          0.140121    1.24451635]
info: {}